### ISSUE TITLE
Spawn resets every restart

### ISSUE THREAD

**Issue by Soapdevs** [LABSTORM-MG/BSpawn#1]
Hiya im miner0914 from bukkit forums o/

Server restart prints the following error in console:
![image](https://user-images.githubusercontent.com/75298673/194116401-3c8e3951-74c4-4d40-a5ef-7182b8846bbc.png)

and resets spawn every restart:
![image](https://user-images.githubusercontent.com/75298673/194116466-203bfd16-6f99-472b-8c74-b2ce01eaf3e6.png)

**Comment by LABSTORM-MG** [comment]
Ups i think I know what the issue is, gonna fix it today :)
